function [fitresult, gof] = createGeneralLogistic6Fit(portamentoX, portamentoY)
%CREATEFIT(PORTAMENTOX,PORTAMENTOY)
%  Create a fit.
%
%  Data for 'Logistic6' fit:
%      X Input : portamentoX
%      Y Output: portamentoY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Dec-2014 09:14:16


%% Fit: 'Logistic6'.
[xData, yData] = prepareCurveData( portamentoX, portamentoY );

% Set up fittype and options.
ft = fittype( 'L + (U-L)/((1+A*exp(-G*(x-M)))^(1/B))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';

%the starting point of the L and U is the minmum and maximum of the pitch
%contour. It greatly improves the fitting performance.
startPointL = min(portamentoY);     
startPointU = max(portamentoY);

            %A  B   G  L M U
opts.Lower = [0 0 -Inf 1 0 1];  

opts.StartPoint = [0.8763 1 0 startPointL 0.1 startPointU];   %for continous note transition

% if startPointL <= startPointU
%     startPointG = 200;
% else
%     startPointG = -200;
% end
% opts.StartPoint = [0.8763 1 0 startPointL 0.1 startPointU];   %for discrete note transition

opts.Upper = [Inf Inf Inf 128 Inf 128];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.0
% fontSize = 30;
% figure( 'Name', 'Logistic Model' );
% %-------get the fitted line-----------
% fittedCoefficientLogistic = coeffvalues(fitresult);
% A = fittedCoefficientLogistic(1); B = fittedCoefficientLogistic(2); G = fittedCoefficientLogistic(3); L = fittedCoefficientLogistic(4); M = fittedCoefficientLogistic(5); U = fittedCoefficientLogistic(6);
% fittedY = L + (U-L)./((1+A*exp(-G*(xData-M))).^(1/B));
%----------------------
% plot( xData, yData,'LineWidth',2);
% hold on
% plot(xData,fittedY,'r--','LineWidth',2);
% hold off
% xlim([xData(1) xData(end)]);
% legend('Note Transition', 'Logistic Model Fitting', 'Location', 'NorthWest' );
% % Label axes
% xlabel( 'T(sec)', 'FontSize', fontSize);
% ylabel( 'Pitch(Midi Number)', 'FontSize', fontSize);
% title('Logistic Model','FontWeight','bold', 'FontSize', fontSize);
% set(gca, 'FontSize', fontSize);
% grid on


